# Generated by Django 3.2.5 on 2021-07-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
