# Generated by Django 3.2.5 on 2021-07-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
