# Generated by Django 3.2.5 on 2021-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_user_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
