# Generated by Django 3.2.5 on 2021-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
